@extends('layouts.app')

@section('title', 'Quản lý văn phòng phẩm')
@section('page-title', 'Quản lý văn phòng phẩm')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h4 class="mb-0">Quản lý văn phòng phẩm</h4>
        <small class="text-muted">Thêm, sửa, xóa và import văn phòng phẩm</small>
    </div>
    <div>
        <a href="{{ route('office-supplies.import.form') }}" class="btn btn-success me-2">
            <i class="fas fa-upload me-2"></i>
            Import Excel/CSV
        </a>
        <a href="{{ route('office-supplies.create') }}" class="btn btn-primary">
            <i class="fas fa-plus me-2"></i>
            Thêm văn phòng phẩm
        </a>
    </div>
</div>

<!-- Filter Section -->
<div class="card mb-4">
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-3">
                <label class="form-label">Danh mục</label>
                <select id="categoryFilter" class="form-select">
                    <option value="">Tất cả danh mục</option>
                </select>
            </div>
            <div class="col-md-3">
                <label class="form-label">Trạng thái</label>
                <select id="statusFilter" class="form-select">
                    <option value="">Tất cả</option>
                    <option value="1">Đang hoạt động</option>
                    <option value="0">Ngưng hoạt động</option>
                </select>
            </div>
            <div class="col-md-4">
                <label class="form-label">Tìm kiếm</label>
                <input type="text" id="searchInput" class="form-control" placeholder="Nhập tên văn phòng phẩm...">
            </div>
            <div class="col-md-2">
                <label class="form-label">&nbsp;</label>
                <button id="filterBtn" class="btn btn-outline-primary w-100">
                    <i class="fas fa-search me-2"></i>Lọc
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Office Supplies Table -->
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="suppliesTable">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Tên văn phòng phẩm</th>
                        <th>Danh mục</th>
                        <th>Đơn vị</th>
                        <th>Giá (VNĐ)</th>
                        <th>Tồn kho</th>
                        <th>Trạng thái</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody id="suppliesTableBody">
                    <tr>
                        <td colspan="8" class="text-center py-4">
                            <div class="spinner-border text-primary" role="status">
                                <span class="visually-hidden">Đang tải...</span>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <nav aria-label="Page navigation" class="mt-4">
            <ul class="pagination justify-content-center" id="pagination">
                <!-- Pagination will be generated by JavaScript -->
            </ul>
        </nav>
    </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="editSupplyModal" tabindex="-1" aria-labelledby="editSupplyModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editSupplyModalLabel">Chỉnh sửa văn phòng phẩm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="editSupplyForm">
                <div class="modal-body">
                    <input type="hidden" id="editSupplyId">
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label for="editName" class="form-label">Tên văn phòng phẩm *</label>
                            <input type="text" class="form-control" id="editName" required>
                        </div>
                        <div class="col-md-6">
                            <label for="editCategory" class="form-label">Danh mục *</label>
                            <input type="text" class="form-control" id="editCategory" required>
                        </div>
                        <div class="col-12">
                            <label for="editDescription" class="form-label">Mô tả</label>
                            <textarea class="form-control" id="editDescription" rows="3"></textarea>
                        </div>
                        <div class="col-md-4">
                            <label for="editUnit" class="form-label">Đơn vị *</label>
                            <input type="text" class="form-control" id="editUnit" required>
                        </div>
                        <div class="col-md-4">
                            <label for="editPrice" class="form-label">Giá (VNĐ) *</label>
                            <input type="number" class="form-control" id="editPrice" min="0" step="0.01" required>
                        </div>
                        <div class="col-md-4">
                            <label for="editStockQuantity" class="form-label">Số lượng tồn *</label>
                            <input type="number" class="form-control" id="editStockQuantity" min="0" required>
                        </div>
                        <div class="col-12">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="editIsActive">
                                <label class="form-check-label" for="editIsActive">
                                    Đang hoạt động
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
let supplies = [];
let filteredSupplies = [];
let currentPage = 1;
const itemsPerPage = 10;

// Load supplies data
async function loadSupplies() {
    try {
        const response = await fetch('{{ route('office-supplies.admin') }}');
        supplies = await response.json();
        filteredSupplies = [...supplies];
        populateCategoryFilter();
        renderTable();
    } catch (error) {
        console.error('Error loading supplies:', error);
        showAlert('Có lỗi xảy ra khi tải dữ liệu', 'danger');
    }
}

// Populate category filter
function populateCategoryFilter() {
    const categories = [...new Set(supplies.map(s => s.category))];
    const select = document.getElementById('categoryFilter');
    select.innerHTML = '<option value="">Tất cả danh mục</option>';
    categories.forEach(category => {
        select.innerHTML += `<option value="${category}">${category}</option>`;
    });
}

// Filter supplies
function filterSupplies() {
    const categoryFilter = document.getElementById('categoryFilter').value;
    const statusFilter = document.getElementById('statusFilter').value;
    const searchInput = document.getElementById('searchInput').value.toLowerCase();

    filteredSupplies = supplies.filter(supply => {
        const matchesCategory = !categoryFilter || supply.category === categoryFilter;
        const matchesStatus = statusFilter === '' || supply.is_active.toString() === statusFilter;
        const matchesSearch = !searchInput || supply.name.toLowerCase().includes(searchInput);
        
        return matchesCategory && matchesStatus && matchesSearch;
    });

    currentPage = 1;
    renderTable();
}

// Render table
function renderTable() {
    const tbody = document.getElementById('suppliesTableBody');
    const start = (currentPage - 1) * itemsPerPage;
    const end = start + itemsPerPage;
    const pageSupplies = filteredSupplies.slice(start, end);

    if (pageSupplies.length === 0) {
        tbody.innerHTML = `
            <tr>
                <td colspan="8" class="text-center py-4 text-muted">
                    <i class="fas fa-inbox fa-2x mb-2"></i><br>
                    Không có văn phòng phẩm nào
                </td>
            </tr>
        `;
        document.getElementById('pagination').innerHTML = '';
        return;
    }

    tbody.innerHTML = pageSupplies.map((supply, index) => `
        <tr>
            <td>${start + index + 1}</td>
            <td>
                <strong>${supply.name}</strong>
                ${supply.description ? `<br><small class="text-muted">${supply.description}</small>` : ''}
            </td>
            <td><span class="badge bg-info">${supply.category}</span></td>
            <td>${supply.unit}</td>
            <td>${new Intl.NumberFormat('vi-VN').format(supply.price)}</td>
            <td>${supply.stock_quantity}</td>
            <td>
                ${supply.is_active 
                    ? '<span class="badge bg-success">Hoạt động</span>' 
                    : '<span class="badge bg-secondary">Ngưng hoạt động</span>'}
            </td>
            <td>
                <button class="btn btn-sm btn-outline-primary me-1" onclick="editSupply(${supply.id})" title="Chỉnh sửa">
                    <i class="fas fa-edit"></i>
                </button>
                <button class="btn btn-sm btn-outline-danger" onclick="deleteSupply(${supply.id})" title="Xóa">
                    <i class="fas fa-trash"></i>
                </button>
            </td>
        </tr>
    `).join('');

    renderPagination();
}

// Render pagination
function renderPagination() {
    const totalPages = Math.ceil(filteredSupplies.length / itemsPerPage);
    const pagination = document.getElementById('pagination');
    
    if (totalPages <= 1) {
        pagination.innerHTML = '';
        return;
    }

    let paginationHTML = '';
    
    // Previous button
    paginationHTML += `
        <li class="page-item ${currentPage === 1 ? 'disabled' : ''}">
            <a class="page-link" href="#" onclick="changePage(${currentPage - 1})">Trước</a>
        </li>
    `;
    
    // Page numbers
    for (let i = 1; i <= totalPages; i++) {
        if (i === 1 || i === totalPages || (i >= currentPage - 2 && i <= currentPage + 2)) {
            paginationHTML += `
                <li class="page-item ${currentPage === i ? 'active' : ''}">
                    <a class="page-link" href="#" onclick="changePage(${i})">${i}</a>
                </li>
            `;
        } else if (i === currentPage - 3 || i === currentPage + 3) {
            paginationHTML += `<li class="page-item disabled"><span class="page-link">...</span></li>`;
        }
    }
    
    // Next button
    paginationHTML += `
        <li class="page-item ${currentPage === totalPages ? 'disabled' : ''}">
            <a class="page-link" href="#" onclick="changePage(${currentPage + 1})">Tiếp</a>
        </li>
    `;
    
    pagination.innerHTML = paginationHTML;
}

// Change page
function changePage(page) {
    const totalPages = Math.ceil(filteredSupplies.length / itemsPerPage);
    if (page >= 1 && page <= totalPages) {
        currentPage = page;
        renderTable();
    }
}

// Edit supply
function editSupply(id) {
    const supply = supplies.find(s => s.id === id);
    if (!supply) return;

    document.getElementById('editSupplyId').value = supply.id;
    document.getElementById('editName').value = supply.name;
    document.getElementById('editCategory').value = supply.category;
    document.getElementById('editDescription').value = supply.description || '';
    document.getElementById('editUnit').value = supply.unit;
    document.getElementById('editPrice').value = supply.price;
    document.getElementById('editStockQuantity').value = supply.stock_quantity;
    document.getElementById('editIsActive').checked = supply.is_active;

    new bootstrap.Modal(document.getElementById('editSupplyModal')).show();
}

// Update supply
async function updateSupply(formData) {
    try {
        const id = formData.get('id');
        const response = await fetch(`/office-supplies/${id}`, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
            },
            body: JSON.stringify({
                name: formData.get('name'),
                category: formData.get('category'),
                description: formData.get('description'),
                unit: formData.get('unit'),
                price: parseFloat(formData.get('price')),
                stock_quantity: parseInt(formData.get('stock_quantity')),
                is_active: formData.get('is_active') === 'on'
            })
        });

        const result = await response.json();
        
        if (result.success) {
            showAlert(result.message, 'success');
            bootstrap.Modal.getInstance(document.getElementById('editSupplyModal')).hide();
            loadSupplies();
        } else {
            showAlert('Có lỗi xảy ra khi cập nhật', 'danger');
        }
    } catch (error) {
        console.error('Error updating supply:', error);
        showAlert('Có lỗi xảy ra khi cập nhật', 'danger');
    }
}

// Delete supply
async function deleteSupply(id) {
    if (!confirm('Bạn có chắc chắn muốn xóa văn phòng phẩm này?')) return;

    try {
        const response = await fetch(`/office-supplies/${id}`, {
            method: 'DELETE',
            headers: {
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
            }
        });

        const result = await response.json();
        
        if (result.success) {
            showAlert(result.message, 'success');
            loadSupplies();
        } else {
            showAlert('Có lỗi xảy ra khi xóa', 'danger');
        }
    } catch (error) {
        console.error('Error deleting supply:', error);
        showAlert('Có lỗi xảy ra khi xóa', 'danger');
    }
}

// Show alert
function showAlert(message, type) {
    const alertHTML = `
        <div class="alert alert-${type} alert-dismissible fade show" role="alert">
            ${message}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    `;
    
    document.querySelector('.container-fluid').insertAdjacentHTML('afterbegin', alertHTML);
    
    setTimeout(() => {
        const alert = document.querySelector('.alert');
        if (alert) alert.remove();
    }, 5000);
}

// Event listeners
document.addEventListener('DOMContentLoaded', function() {
    loadSupplies();

    // Filter button
    document.getElementById('filterBtn').addEventListener('click', filterSupplies);

    // Search input
    document.getElementById('searchInput').addEventListener('keyup', function(e) {
        if (e.key === 'Enter') {
            filterSupplies();
        }
    });

    // Edit form submission
    document.getElementById('editSupplyForm').addEventListener('submit', function(e) {
        e.preventDefault();
        const formData = new FormData();
        formData.append('id', document.getElementById('editSupplyId').value);
        formData.append('name', document.getElementById('editName').value);
        formData.append('category', document.getElementById('editCategory').value);
        formData.append('description', document.getElementById('editDescription').value);
        formData.append('unit', document.getElementById('editUnit').value);
        formData.append('price', document.getElementById('editPrice').value);
        formData.append('stock_quantity', document.getElementById('editStockQuantity').value);
        if (document.getElementById('editIsActive').checked) {
            formData.append('is_active', 'on');
        }
        updateSupply(formData);
    });
});
</script>
@endpush